### ISSUE TITLE
Some question about dbfv in lattigo

### ISSUE THREAD

**Issue by 1180300419** [ldsec/lattigo#101]
Hi, I read the paper titled _Multiparty Homomorphic Encryption from Ring-Learning-With-Errors_. And I have a question about it.

I noticed that during the decryption step, a participant can recover the private key after acquiring all the secret shares. 

So, is there a single point of failure: an adversary who compromises the combiner during decryption will learn secret key in the clear? If so, what can be done to avoid it?

Thank you!

**Comment by Pro7ech** [comment]
Hi Xiaohui Liu,

Given ct = [-a * s + m + e, a] with s = sum(s_i), the decryption shares are of the form [a*s_i + e_i], hence they are valid R-LWE sample and do not leak information about the individual s_i. The decryption process is to sum those R-LWE samples on the ciphertext. Therefore, at no point during the decryption is the ideal secret _s_ exposed, nor are the individuals _s_i_.

Did that answer your question?

**Comment by 1180300419** [comment]
I am so sorry. I understand the ambiguity. There is no single point of failure. Thank you again.

**Comment by bo-hub** [comment]
@Pro7ech , Is there any sample program for the decryption process, i.e given decryption shares, add them together to get a recover message.
