### ISSUE TITLE
Possible bug due to unhandled uint64 overflow in CKKS encoding

### ISSUE THREAD

**Issue by msh086** [ldsec/lattigo#102]
In ckks/utils.go, this function first scales the inputted float64 vector, then converts it into a polynomial in non-NTT form, as part of plaintext encoding in CKKS
https://github.com/ldsec/lattigo/blob/886030256362cb9eb6c4def5a5e77d2305138ffb/ckks/utils.go#L38
and the following line checks if the magnitude of a coefficient is larger than 64 bits to prevent an overflow
https://github.com/ldsec/lattigo/blob/886030256362cb9eb6c4def5a5e77d2305138ffb/ckks/utils.go#L47
but I think here we should check the magnitude of, for example `math.Abs(n*values[i])` instead of `n*values[i]`?

**Comment by Pro7ech** [comment]
Hi msh086, 

You are correct, n*math.Abs(values[i]) should be called instead.

Thank you very much for pointing out this issue
