### ISSUE TITLE
880 / 881

### ISSUE THREAD

**Issue by ineiti** [ldsec/lattigo#103]
Just trying to understand the parameters, I see that

https://github.com/ldsec/lattigo/blob/caabc9baaa4b1132315879c55b02b4e6a539a4ff/ckks/README.md

has `PN15QP881`, while the definition has `PN15QP880`

https://github.com/ldsec/lattigo/blob/caabc9baaa4b1132315879c55b02b4e6a539a4ff/ckks/params.go#L38

It's just an off-by-one error in the README, and I have _no_ idea which one is correct ;)

To underline that I have no idea, the following document has `880`, `881`, and `883` in the tables, and from what I gather, it should be the one in the `{-1, 1}` - but in the README.md you write about a `ternary`, which I cannot find...

https://projects.csail.mit.edu/HEWorkshop/HomomorphicEncryptionStandard2018.pdf

I think I should read up some more on lattice-based crypto ;)

**Comment by ChristianMct** [comment]
Hi @ineiti, 

In the draft standardization document, the `{-1, 1}` tables correspond to _the ternary distribution_ we mention in our README (see section 2.0.3 of the document). When using this distribution and a ring degree of `2^15`, the recommendation for the *largest* secure modulus is 881 bits.

For the current `ckks/params.go` version, `ckks.DefaultParams[ckks.PN15QP880].LogQP()` returns `880` so the name is correct and the modulus is secure.

For the current `ckks/README.md`, the parameter tuples correspond to the values in the draft standard document and not to the default parameters (we can make this explicit or simply remove these tuples).

I hope this helps!

**Comment by ineiti** [comment]
Thanks for the explanation!
