### ISSUE TITLE
Setting the bootstrapping parameter

### ISSUE THREAD

**Issue by mrain** [ldsec/lattigo#109]
What's the recommended way to manually set the bootstrapping parameters?
I tried something simple: https://gist.github.com/mrain/d67b5ce44fb20e8c3b2325e0982937f5 But there might be some scaling problem with the result.

Even in the dev_paper branch, the problem occurs with the default parameter
Part of the test code is pasted here: https://gist.github.com/mrain/be4340153b723502496c054a5f3d618e
And the output is: https://gist.github.com/mrain/64b1f89ba0b1832a077fa4250cfe59da

**Comment by Pro7ech** [comment]
He mrain, 

If I understand correctly, you usethe following moduli chain for the bootstrapping ? 

`LogModuli := ckks.LogModuli{
	LogQi: []uint64{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30}, // 25 depth
	LogPi: []uint64{30, 30},
}`
