### ISSUE TITLE
Is there any plan to welcome contribution for this project

### ISSUE THREAD

**Issue by libratiger** [ldsec/lattigo#113]
It's wonderful using golang to implement the HE, it there any plan for discussion and chat like slack?

Take for example, I want to make a distributed computation engine like Spark, which using the lattigo as the Engine, 

but I do not know how to begin make contribution to this project at first.

**Comment by ChristianMct** [comment]
Hi, @libratiger

Thanks for your interest in the library; we are always happy to learn about new uses of Lattigo. The only communication channels that we have at the moment are GitHub issues and the contact email contact[at]listes.epfl.ch.

Take into account that Lattigo is a working prototype that we developed and extended to support our laboratory's research on HE and multiparty-HE, with limited resources. In this regard, the roadmap is still significantly impacted by internal research projects, and backward compatibility/API stability across versions is not something we can ensure yet.

I hope this helps!

**Comment by libratiger** [comment]
Thanks! @ChristianMct what's the difference between the issue and email? 
is there some discussion in the email group? if so, I would like to join into this.

**Comment by ChristianMct** [comment]
We use issues to keep track of bugs and feature requests as well as questions of general interest. The email is a private alternative to issues. At this stage, I'm afraid we have no public channel of discussion about the development of the library. 

For updates regarding the project, you can track the [releases page](https://github.com/ldsec/lattigo/releases) and the CHANGELOG.md file which we keep in sync with all newly released changes and features.
