### ISSUE TITLE
CKKS/Params is missing GetDataLen

### ISSUE THREAD

**Issue by crockeea** [ldsec/lattigo#115]
Serialization for CKKS `Parameters` doesn't have a `GetDataLen` function, despite a [non-trivial computation](https://github.com/ldsec/lattigo/blob/master/ckks/params.go#L583) of the serialized size. Please add this function.

Also, it's odd that most serialization functions are in ckks/marshaler.go, but the serialization for `Parameters` is in ckks/params.go. Perhaps move `func (p *Parameters) MarshalBinary()`, `func (p *Parameters) UnmarshalBinary(...)`, and `func (p*Parameters) GetDataLen(WithMetaData bool)`. Can these be moved to ckks/marshaler.go for consistency?

**Comment by ChristianMct** [comment]
The `Parameters.MarshalBinarySize` method was added for all schemes in the main branch and the next release will include these methods.
