### ISSUE TITLE
EncodeNTTAtLvlNew ignores the level argument

### ISSUE THREAD

**Issue by crockeea** [ldsec/lattigo#119]
[`EncodeNTTAtLvlNew`](https://github.com/ldsec/lattigo/blob/0fcda6821641611bb36f57d1c1df3ad0f7cec06d/ckks/encoder.go#L148) ignores the level argument and instead uses `encoder.params.MaxLevel()`. This means that plaintexts will be encoded at the wrong level if `level != MaxLevel()`.

**Comment by ChristianMct** [comment]
Thanks for reporting this issue. This is indeed not the correct behavior.
