### ISSUE TITLE
code should be golint-clean

### ISSUE THREAD

**Issue by cgrigis** [ldsec/lattigo#12]
Hello,

Running `golint ./...` at the root directory lists a few issues (minor things such as underscore in names, `+= 1` --> `++`, missing comments).
For code quality purposes, I would suggest to fix these, as well as adding a `lint` step in the CI chain to ensure it remains clean.

Thank you!

**Comment by ChristianMct** [comment]
One of our next focus is to improve our testing/benchmarking/CI pipeline. So this suggestion comes right on time.
