### ISSUE TITLE
Is there a way to save keys to disk?

### ISSUE THREAD

**Issue by jayavanth** [ldsec/lattigo#126]

**Comment by jayavanth** [comment]
Thanks! It works for public and private encryption keys but when I try it for Bootstrap, Relinearization and Rotation keys, I get 
```
 btpKey.MarshalBinary undefined (type *ckks.BootstrappingKey has no field or method MarshalBinary)
```

**Comment by ChristianMct** [comment]
You are correct, the latest `v2.1.1` release does not have a serializer for the `ckks.BootstrappingKey` type.

Unfortunately, there is no workaround to this problem for this version as the fields of this type are private. However, this is not the case on the `master` branch which contains our latest improvements to the keys and to the bootstrapping. We plan to release a version that includes these changes soon, so this situation is temporary.

**Comment by Pro7ech** [comment]
The direct marshaling for bootstrapping keys are indeed currently missing but we have plans to add them in the near future. In the mean time, a `ckks.BootstrappingKey` is no more than a wrapper for an `rlwe.EvaluationKey{Rlk:rlwe.RelinearizationKey, Rtks:rlwe.RotationkeySet`, so you should be able to marshal it by individually marshalling the subfields.

**Comment by jayavanth** [comment]
Thanks!
