### ISSUE TITLE
128-bit security while bootstrapping with logN < 15?

### ISSUE THREAD

**Issue by jayavanth** [ldsec/lattigo#129]
Can I achieve 128-bit security while keeping logN low? I want to keep logN low to bootstrap on a computer with low RAM (~4GB). I see that there are 5 sets of params in `bootstrap_params.go` but they are all with logN=16 or 15. Is there a formula or rule to follow to find out params such that logN=10 and security is 128-bit?

**Comment by Pro7ech** [comment]
Hi @jayavanth,

The library provides default parameters that are at least 128-bit secure according to the community standard (https://homomorphicencryption.org/standard/). It is possible to use custom parameters but anyone doing so should be aware of the security implications. Unfortunately, we cannot provide any support regarding custom parameter sets and their security.

I can however still give a partial answer to your question: the implemented bootstrapping circuit is quite large and thus requires a large modulus size too. The maximum modulus size for logN=15 is already at the limit for these requirements. Hence, for the implemented bootstrapping procedure (as-well-as for all known methods), there is no secure and bootstrapable parameters with logN below 15.

**Comment by jayavanth** [comment]
Thanks! That makes sense
