### ISSUE TITLE
CKKS bootstrapping randomly returns ciphertext with incorrect data

### ISSUE THREAD

**Issue by FongChanatip** [ldsec/lattigo#134]
Hi!

I am using this library to do some computation on the CKKS ciphertext that requires a lot of bootstrapping and I have notice that sometimes after bootstrapping, the data inside the output ciphertext was incorrect; however, this problem only occurs some of the time, meaning that if I run the same code twice one might return the correct result, and the other might fail. After looking through [this paper](https://eprint.iacr.org/2020/1203.pdf), I have notice that it mentioned bootstrapping failure probability; therefore, I would like to know if this issue is related to the bootstrapping failure mentioned in the paper or not, and, if it is, is there any way to prevent it from happening, or to check if it had happened (without decrypting the ciphertext). 

For the parameter, I am using the `ckks.DefaultBootstrapSchemeParams[0]` as a ciphertext params and `ckks.DefaultBootstrapParams[0]` for bootstrapping params. I am using v2.1.1 of this library.

Thanks.

**Comment by Pro7ech** [comment]
Hi FongChanatip, 

The bootstrapping parameters in v2.1.1. were set before a throughout failure probability analysis, and aren't the ones showcased in our paper. You can use the ones present in the latest code of the master as they are the ones of our paper. This should solve your problem. Note that there will always be a non zero probability of failure but it should this time be negligible.

**Comment by FongChanatip** [comment]
Thank you! I'll try that out.
