### ISSUE TITLE
Question about comparison of encrypted data using bfv

### ISSUE THREAD

**Issue by r0qs** [ldsec/lattigo#136]
Hi, I am playing with your bfv implementation, and I am getting some strange results. But as homomorphic encryption is still very new to me, I suspect that I'm doing something wrong, but I don't know exactly what.

Below is an example that I made to illustrate the problem (it uses the latest master branch f43eec6). Although the result of both operations below are correct when decrypted, the comparison of the inline ring is not. Is this an expected behavior? There is any way that I can perform integer comparison between the encrypted data?

```go
package main

import (
	"fmt"

	"github.com/ldsec/lattigo/v2/bfv"
	"github.com/ldsec/lattigo/v2/rlwe"
)

var params bfv.Parameters

func init() {
	var err error
	paramDef := bfv.PN13QP218
	paramDef.T = 0x3ee0001
	params, err = bfv.NewParametersFromLiteral(paramDef)
	if err != nil {
		panic(err)
	}
}

func main() {
	kgen := bfv.NewKeyGenerator(params)
	sk, pk := kgen.GenKeyPair()

	encryptor := bfv.NewEncryptorFromPk(params, pk)
	decryptor := bfv.NewDecryptor(params, sk)
	encoder := bfv.NewEncoder(params)
	evaluator := bfv.NewEvaluator(params, rlwe.EvaluationKey{})

	opValue := []int64{3}

	op1Plaintext := bfv.NewPlaintext(params)
	encoder.EncodeInt(opValue, op1Plaintext)
	op1 := encryptor.EncryptNew(op1Plaintext)

	op2Plaintext := bfv.NewPlaintext(params)
	encoder.EncodeInt(opValue, op2Plaintext)
	op2 := encryptor.EncryptNew(op1Plaintext)

	// result should be op1: y = 3 + 3 - 3
	result := evaluator.SubNew(evaluator.AddNew(op1, op2), op2) 

	decoded := encoder.DecodeIntNew(decryptor.DecryptNew(result))
	fmt.Println("result:", int64(decoded[0]))

	if checkResult(result, op1) { // this works (returns true)
		fmt.Println("result equal to op1")
	} else {
		fmt.Println("result not equal to op1")
	}

	onePlaintext := bfv.NewPlaintext(params)
	encoder.EncodeInt([]int64{1}, onePlaintext)
	one := encryptor.EncryptNew(onePlaintext)

	// result should be one: y = 3 + 1 - 3
	result = evaluator.SubNew(evaluator.AddNew(op1, one), op2)

	decoded = encoder.DecodeIntNew(decryptor.DecryptNew(result))
	fmt.Println("result:", int64(decoded[0]))

	if checkResult(result, one) {  // this doesn't work (returns false)
		fmt.Println("result equal to one")
	} else {
		fmt.Println("result not equal to one")
	}
}

func checkResult(a *bfv.Ciphertext, b *bfv.Ciphertext) bool {
	for i := range a.Value {
		if !params.RingQ().Equal(a.Value[i], b.Value[i]) {
			return false
		}
	}
	return true
}
```

If I replace the second operation by this:
```go
result = evaluator.SubNew(evaluator.AddNew(op1, one), op1)
```
The comparison works fine, but it seems to be a false positive, and I think such comparison mechanism is actually wrong. So I wonder how I can compare encrypted data.

**Comment by techwday** [comment]
My understanding is it's not easy to compare two values using BVF. However there us some recent research that paves a way for easier comparison of values using BVF. I'm trying to implement it in one of my programs using Lattigo.

https://eprint.iacr.org/2021/315.pdf

**Comment by Pro7ech** [comment]
You can compare two values by evaluating 1-(x-y)^(p-1), which can be done in log(p) +hw(p) multiplications using a square and multiply algorithm. It will return 1 if x=y, else 0.

**Comment by techwday** [comment]
@Pro7ech is comparison something your team is working on in the library?

**Comment by r0qs** [comment]
> My understanding is it's not easy to compare two values using BFV. However there is some recent research that paves a way for easier comparison of values using BFV. I'm trying to implement it in one of my programs using Lattigo.
> 
> https://eprint.iacr.org/2021/315.pdf

Thank you very much for the reference @techwday I'll take a look at it.

> You can compare two values by evaluating 1-(x-y)^(p-1), which can be done in log(p) +hw(p) multiplications using a square and multiply algorithm. It will return 1 if x=y, else 0.

And thanks @Pro7ech this was exactly what I was looking for now! :-)

**Comment by Pro7ech** [comment]
@r0qs The result will be encrypted, so to check it you will need to decrypt and decode the result.
@techwday We do not plan to add such features to the libraries unless they are already considered as an intrinsic of the related scheme, which is not the case for BFV and CKKS.

**Comment by r0qs** [comment]
I see. Thanks anyway @Pro7ech for the clarification, but I believe bfv will not work in my use case since I need to perform comparison between an encrypted integer set in the server side. I'll take a look in the alternative paper that @techwday sent and see what I can do.
