### ISSUE TITLE
Reuse bootstrapping keys for evaluation

### ISSUE THREAD

**Issue by crockeea** [ldsec/lattigo#137]
In Lattigo v2.1.1, the `BootstrappingKey` rotation and relinearization keys are not exported, so they cannot be re-used during evaluation. The result is that I have to generate rotation keys, relinearization keys, _and_ bootstrapping keys (which in many cases will be a superset of the former keys), serialize all of them, and send them to the server. This double memory and communication. Is there a way around this issue?

**Comment by ChristianMct** [comment]
Hi @crockeea,

Thanks for reporting this issue, but I'm afraid there is no solution in v2.1.1. 

However, as mentioned in #138, there will be a version release this week that brings a lot of improvements to the keys and key-generation procedures. In this new version, the `ckks.BootstrappingKey` type has public fields which enables the standalone use of the underlying relinearization and rotation keys.

**Comment by crockeea** [comment]
I also noticed that there's no way to serialize bootstrapping keys; will this be possible with the new API?

**Comment by ChristianMct** [comment]
In the new interface, the `ckks.BootstrappingKey` type is an alias for generic `rlwe.EvaluationKey` and 

```
package rlwe

type EvaluationKey struct {
	Rlk  *RelinearizationKey
	Rtks *RotationKeySet
}
```

where both `RelinearizationKey` and `RotationKeySet` types implement the `BinaryMarshaler` interface. So, you will be able to serialize bootstrapping keys in two calls. Given the usual size of bootstrapping keys and the facts that you mentioned above, we were not planning to implement `BinaryMarshaler` directly for `ckks.BootstrappingKey`. We might however provide a more convient interface to read and write them to streams in upcoming release.

**Comment by Pro7ech** [comment]
Note that it is also possible to serialize each rotation key individually by looping over the map.
