### ISSUE TITLE
Why the need for "utils.Buffer"?

### ISSUE THREAD

**Issue by cgrigis** [ldsec/lattigo#14]
[Please label this as "question" :-)]

I was just curious, why was the `Buffer` type in package `utils` written? If I am not mistaken, it looks like the standard [`bytes.Buffer`](https://golang.org/pkg/bytes/#Buffer) type, along with the [`binary.Read`](https://golang.org/pkg/encoding/binary/#Read) and [`binary.Write`](https://golang.org/pkg/encoding/binary/#Write) functions, would provide the same functionality? Or is it for reasons of performance?

**Comment by ChristianMct** [comment]
Your guess is correct. The `binary.Write` method allocates memory whereas our buffer implementation does not.
