### ISSUE TITLE
Add support for serializing ckks.BootstrappingParameters

### ISSUE THREAD

**Issue by crockeea** [ldsec/lattigo#140]
I don't see a `MarshalBinary` API for `BootstrappingParameters`. Without serialization/deserialization for bootstrapping parameters, I can't send these parameters from a client to a server, and without the parameters, the server cannot create a `Bootstrapper`.

**Comment by Pro7ech** [comment]
Hi @crockeea, we are aware of the missing features of the current bootstrapping implementation and are actively working on a full re-implementation, more user oriented, of the bootstrapping. In the mean time you can use `encoding/gob` to serialize the bootstrapping parameters.
