### ISSUE TITLE
Bootstrapp should not modify input

### ISSUE THREAD

**Issue by crockeea** [ldsec/lattigo#141]
Currently, `Bootstrapp` is defined as 
```
func (btp *Bootstrapper) Bootstrapp(ct *Ciphertext) *Ciphertext
```
So it takes a ciphertext and outputs a bootstrapped ciphertext. This strongly suggests that the input is _not_ modified, but for some reason, `Bootstrapp` modifies the input _and_ returns a different output. This is neither intuitive nor documented. I suggest making `Bootstrapp` return a new value without modifying the input.

**Comment by Pro7ech** [comment]
Hi @crockeea, 

Thank you for your feedback. We will include this to the upcoming bootstrapping pull request (PR #139).
