### ISSUE TITLE
Unable to use concurrency goroutine when doing operation with CKKS ciphertext

### ISSUE THREAD

**Issue by FongChanatip** [ldsec/lattigo#143]
Currently, I'm trying to use goroutine to perform some operation on different ciphertext simultaneously, but I found out that those operations return an unexpected result; for example, when decrypting different ciphertexts on parallel goroutines, the decryption returns `[(NaN+NaNi) (NaN+NaNi) ...]` after decode. This also happens with other operations, such as **bootstrapping**. To check that I didn't do anything wrong, I tried calling `timer.Sleep(500 * time.Millisecond)` after starting a decryption goroutine and the results were correct; thus, I'd like to know, if any of you know, what went wrong. 

Thank you so much

I'm using v.2.2.0 of this library (with default bootstrapping params index 0), and here's the code that caused this issue

```go

// Function for decrypting multiple ciphertexts in an array at the same time.
func DecryptCts(ct []*ckks.Ciphertext, encoder ckks.Encoder, decryptor ckks.Decryptor, logSlots int) [][]float64 {

	// Generate slice of channels to capture return value from goroutine
	channels := make([]chan []float64, len(ct))

	for i := range ct{

		channels[i] = make(chan []float64)

		// Start go routine
		go bootstrapGoRoutine(*ct[i], encoder, decryptor, logSlots, channels[i])

		// Uncommenting the line below will eliminate this problem, but won't suit the purpose of this code.
		// time.Sleep(500 * time.Millisecond)

	}

	result := make([][]float64, len(ct))

	for c := range channels{
		// Capture retuen value
		result[c] = <- channels[c]
	}

	return result

}

// GoRoutine function
func bootstrapGoRoutine (ciphertext ckks.Ciphertext, encoder ckks.Encoder, decryptor ckks.Decryptor, logSlots int, c chan []float64){

	// Copy ciphertext; if removed, will caused error (idk why).
	ct := ciphertext.CopyNew()
	pt := decryptor.DecryptNew(ct)
	decoded := encoder.Decode(pt, logSlots)
	
	result := make([]float64, int(math.Pow(2, float64(logSlots))))

	fmt.Println(decoded[0:10])

	for i := range decoded{
		// Convert complex to float
		result[i] = real(decoded[i])
	}

	c <- result

}

```

Also sometimes, instead of incorrect result, it returns this error message

```
panic: underflow

goroutine 7 [running]:
math/big.nat.sub(0xc176b5cb40, 0x14, 0x18, 0xc0001d0840, 0x14, 0x18, 0xc176b5cb40, 0x14, 0x18, 0xc176ad5c80, ...)
        /usr/local/go/src/math/big/nat.go:147 +0x40b
math/big.(*Int).Sub(0xc176b568e0, 0xc176b568e0, 0xc00ad3a5a0, 0xc176b568e0)
        /usr/local/go/src/math/big/int.go:150 +0x25a
github.com/ldsec/lattigo/v2/ckks.polyToComplexCRT(0xc00ad3a5e0, 0xc157800000, 0x10000, 0x10000, 0xc158702000, 0x8000, 0x8000, 0x4220000000000000, 0xf, 0xc00010e900, ...)
        /Users/Fong/go/pkg/mod/github.com/ldsec/lattigo/v2@v2.2.0/ckks/encoder.go:327 +0x298
github.com/ldsec/lattigo/v2/ckks.(*encoderComplex128).plaintextToComplex(0xc000134000, 0x18, 0x4220000000000000, 0xf, 0xc00ad3a5e0, 0xc158702000, 0x8000, 0x8000)
        /Users/Fong/go/pkg/mod/github.com/ldsec/lattigo/v2@v2.2.0/ckks/encoder.go:345 +0x173
github.com/ldsec/lattigo/v2/ckks.(*encoderComplex128).decodePublic(0xc000134000, 0xc000012da0, 0xf, 0x0, 0xc00010e5a0, 0xf, 0x4270000000000000)
        /Users/Fong/go/pkg/mod/github.com/ldsec/lattigo/v2@v2.2.0/ckks/encoder.go:575 +0x225
github.com/ldsec/lattigo/v2/ckks.(*encoderComplex128).Decode(0xc000134000, 0xc000012da0, 0xf, 0x0, 0x0, 0x0)
        /Users/Fong/go/pkg/mod/github.com/ldsec/lattigo/v2@v2.2.0/ckks/encoder.go:279 +0x48
main.bootstrapGoRoutine(0xc0005323f0, 0x4220000000000000, 0x1274ce8, 0xc000134000, 0x1272058, 0xc000505280, 0xf, 0xc0000287e0)
        /Users/Fong/go/src/github.com/FongChanatip/test/main.go:40 +0xc2
created by main.DecryptCts
        /Users/Fong/go/src/github.com/FongChanatip/test/main.go:21 +0xe5
exit status 2
```

**Comment by Pro7ech** [comment]
Hi @FongChanatip, 

This is an expected behavior,  the library's structs internal memory pools are not thread-safe. To be able to use concurrency you must duplicate those structs. The `evaluator` has for example the method `.ShallowCopy()`, which returns a copy of the current evaluator but with a separate internal memory pool.

**Comment by FongChanatip** [comment]
Ah, I see. Is there a recommended way to do a copy of the `ckks.Bootstrapper`?

Thanks!

**Comment by Pro7ech** [comment]
You bring a good point. Although the evaluation keys are read-only and can be used concurrently by all evaluators/bootstrappers, creating a new `ckks.Bootstrapper` will generate new plaintext matrices for the homomorphic encoding, which is inefficient. We are currently working on the PR#139, whose aim is to improve the user experience of using advanced functionalities of the CKKS scheme, like the bootstrapping. I will add a `.ShallowCopy` for the bootsrapper in this PR that will allow to create light copies of the original bootstrapper for concurency use. We plan to merge this PR in the coming days.

**Comment by FongChanatip** [comment]
That's fantastic. I'm looking forward to use it!

Thanks again.

**Comment by Pro7ech** [comment]
I added the `.ShallowCopy(\*)` for `ckks/advanced.Evaluator` and `ckks/bootstrapping.Bootstrapper`. You can check the PR.

**Comment by FongChanatip** [comment]
Ah, thank you so much!
