### ISSUE TITLE
Lattigo over the network

### ISSUE THREAD

**Issue by RasoulAM** [ldsec/lattigo#157]
Hello,

I need to use Lattigo to run a protocol over the network (a two-party protocol). Is there any implementation of Lattigo over the network, including serializers and deserializers? If not do you have any suggestions on libraries that do networking using Go?

**Comment by ChristianMct** [comment]
Hi @RasoulAM,

The cryptographic objects of Lattigo implement the  `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` interfaces for `[]byte` serialization and deserialization.

To implement a two-party protocol with Go, and assuming that you can express the protocol in terms of a client-server interaction, I would consider [gRPC](https://grpc.io/).

**Comment by RasoulAM** [comment]
Thanks
