### ISSUE TITLE
A question about the InnerSum function in ckks algorithm

### ISSUE THREAD

**Issue by YNZJ667** [ldsec/lattigo#160]
When I use InnerSum function to computer the inner sum of a ciphertext, I have a problem. If n > 3 or batchsize >= 3 , the program will report an error “panic: switching key not available”. Otherwise, there are some number that given in n, such as 15, 19 and so on, also causing the above prblem when I use InnerSumLog function of CKKS algorithm. Therefore, how should I choose a number of n and batchsize, and are there any parameter selection rules about it? In addition, when n is greater than 3, is the InnerSum function unavailable?

**Comment by Pro7ech** [comment]
Hi @YNZJ667, how are you generating the rotation keys? Are you using the method 

`kgen.GenRotationKeysForRotations(params.RotationsForInnerSum(batch, n), false, sk)`

?
