### ISSUE TITLE
What's means about the hw(n) in algorithm?

### ISSUE THREAD

**Issue by YNZJ667** [ldsec/lattigo#162]
In the analysis of some functions, such as InnerSumLog in ckks.linear_transform, there is "log2(n) + HW(n) rotations with double hoisting". What's means of the HW(n) in this situation?
![image](https://user-images.githubusercontent.com/53722056/147637624-8ac5914c-3342-42a2-b3d6-c3810ef2a976.png)

**Comment by ChristianMct** [comment]
Hi @YNZJ667 , 

HW(n) is the hamming weight of n.

**Comment by YNZJ667** [comment]
> 

Thank you
