### ISSUE TITLE
[Question] Are evaluation keys public?

### ISSUE THREAD

**Issue by r0qs** [ldsec/lattigo#163]
Hi, I implemented a function to compute the inner product of two operands that require relinearization and key rotation. It seems to give the correct output, but how safe is it to share the evaluation keys for relinearization and rotation? Are they supposed to be public, right?

**Comment by Pro7ech** [comment]
Hi @r0qs, 

Yes evaluation keys are public material that can be safely disclosed.

**Comment by r0qs** [comment]
Thanks!
