### ISSUE TITLE
Custom parameter sets

### ISSUE THREAD

**Issue by jimouris** [ldsec/lattigo#174]
Hello,

Is there any straightforward way or a script to generate custom parameters? I want something similar to `PN15QP880` from [bfv.params](https://github.com/ldsec/lattigo/blob/master/bfv/params.go) but with a few more levels.

What is the process in order to generate custom parameters?

Thank you,
Dimitris

**Comment by ChristianMct** [comment]
Hi @jimouris,

Generating custom parameters is done by creating a `bfv/ckks.ParameterLitteral` type passing it to the `bfv/ckks.NewParametersFromLiteral(ParameterLitteral)` function.

For example (taken from [examples/ckks/euler](https://github.com/ldsec/lattigo/tree/master/examples/ckks/euler)), the following code creates a `ckks.Parameter` struct given a moduli chain specified by its moduli sizes in bit:
```
params, err := ckks.NewParametersFromLiteral(ckks.ParametersLiteral{
      LogN:         14,
      LogQ:         []int{55, 40, 40, 40, 40, 40, 40, 40},
      LogP:         []int{45, 45},
      Sigma:        rlwe.DefaultSigma,
      LogSlots:     13,
      DefaultScale: float64(1 << 40),
})
if err != nil {
      panic(err)
}
```

Note that the `ParametersLiteral` also supports specifying the moduli directly, by populating the `ParametersLiteral.Q` and `ParametersLiteral.P` fields. Also, the `NewParametersFromLiteral` function checks that the parameter are correct and within certain bounds, but does not check that they are secure.

Hope this helps!

**Comment by jimouris** [comment]
@ChristianMct awesome, thank you for the quick reply!
