### ISSUE TITLE
Homomorpic encrypted programm

### ISSUE THREAD

**Issue by WolfgangSchulz** [ldsec/lattigo#23]
hi, I am new here,
Could anyone pls give me an code example of an arithmetic programm which is encrypted and decrypted in ckks or any other methode.
Example: 
A String: Hello World
A int: with plus and multiplication

**Comment by ChristianMct** [comment]
Hi,

You can find an arithmetic circuit example for the BFV scheme in the `examples/bfv/examples_bfv.go` file. There is also a (quite minimalist) example for the CKKS scheme in the `example/ckks` package. 
We are currently working on more elaborated and documented examples for both schemes.

Hope this helps.
