### ISSUE TITLE
Issue with older branch

### ISSUE THREAD

**Issue by WolfgangSchulz** [ldsec/lattigo#25]
Hello,
I have found an example of an older version. Now I want to create a code based on it to do some calculations.
https://medium.com/asecuritysite-when-bob-met-alice/heaan-homomorphic-encryption-for-arithmetic-of-approximate-numbers-ckks-40fa6a7a1fb6

Visual Studio says:
""""""""""""""""""""""""""""
undefined: ckks.CkksContext
undefined: ckks.NewCkksContext
encryptor.EncryptNew undefined (type *ckks.Encryptor is pointer to interface, not interface)
decryptor.DecryptNew undefined (type *ckks.Decryptor is pointer to interface, not interface)
""""""""""""""""""""""""""""
what has changed in the ckks file?
where can I find the older package or what do I have to change that it will work?

i hope you can help me
greetings

**Comment by ChristianMct** [comment]
Hi,

What changed is that the latest version simplifies the public interface by making the `CkksContext` object private. Encryptors and similar objects are now created by passing the `ckks.Parameters` struct (and are interface types). We encourage porting code to version `v1.3.0` as its faster and more stable.

To run this example, you can use version `v1.0.1` (you'll have to change the import to point to the new repository). Assuming you are using Go version > 1.11.x, you can do that easily using Go modules. If your project has already a `go.mod` file, simply run:

`go mod init; go get github.com/ldsec/lattigo@v1.0.1`

Hope this helps!

**Comment by WolfgangSchulz** [comment]
thanks, that helped a lot.
 
I have another question. I want to add two strings after they got encrypted so that the homomorphic database will decrypt the result of that calculation. like 12 and 23 enc = 35 dec

can i just change the code from this (Original): 
        // Plaintext creation and encoding process
	plaintext := ckkscontext.NewPlaintext(levels-1, scale)
	plaintext.EncodeComplex(values)
	// Encryption process
	var ciphertext *ckks.Ciphertext
	ciphertext, _ = encryptor.EncryptNew(plaintext)
	// Decryption process
	plaintext, _ = decryptor.DecryptNew(ciphertext)

to this (new)?: 
	// Plaintext creation and encoding process
	plaintext := ckkscontext.NewPlaintext(levels-1, scale)
	plaintext.EncodeComplex(values)
	// Encryption process
	var ciphertext *ckks.Ciphertext
	ciphertext, _ = encryptor.EncryptNew(plaintext)

	// Plaintext2 creation and encoding process
	plaintext2 := ckkscontext.NewPlaintext(levels-1, scale)
	plaintext2.EncodeComplex(values2)
	// Encryption process
	var ciphertext2 *ckks.Ciphertext
	var ciphertext2, _ = encryptor.EncryptNew(plaintext2)

	var cipher = (ciphertext + ciphertext2)

	// Decryption process
	plaintext, _ = decryptor.DecryptNew(cipher)

VSC told me: invalid operation: ciphertext + ciphertext2 (operator + not defined on pointer)

i created a copy of the values and made a "values2" where a str2 used. str:="12" str2:= "23"

can someone pls help me? I don't have enought experience in the go language to get the code working

**Comment by WolfgangSchulz** [comment]
Thanks. That helped a lot
I have another question ...  i have put a txt file reader in it.
Everything works accept of the output. Even the Cipher is there.

What do I need to chang to get the output after "Decrypted:"

I have to be smth in the fmt output process:

Code:
//////////////////////////////////////////////////////////////
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"math"
	"github.com/ldsec/lattigo/ckks"
	"math/big"
	"os"
	"time"
)

func main() {

	// Hier wird die Zeit gemessen
	// Hier wird die Zeit gemessen
	start := time.Now()

	r := new(big.Int)
	fmt.Println(r.Binomial(1000, 10))
	// Hier wird die Zeit gemessen
	// Hier wird die Zeit gemessen

	var logN, logQ, levels, scale uint64

	// Scheme params
	logN = 10
	logQ = 30
	levels = 8
	scale = logQ
	sigma := 3.19

	// Hier wird die txt Datei eingelesen
	// Hier wird die txt Datei eingelesen
	// Read entire file content, giving us little control but
	// making it very simple. No need to close the file.
	content, err := ioutil.ReadFile("file.txt")
	if err != nil {
		log.Fatal(err)
	}

	// Convert []byte to string and print to screen
	str := string(content)
	// Hier wird die txt Datei eingelesen
	// Hier wird die txt Datei eingelesen

	argCount := len(os.Args[1:])

	if argCount > 0 {
		str = string(os.Args[1])
	}

	// Context
	var ckkscontext *ckks.CkksContext
	ckkscontext, _ = ckks.NewCkksContext(logN, logQ, scale, levels, sigma)

	kgen := ckkscontext.NewKeyGenerator()

	// Keys
	var sk *ckks.SecretKey
	var pk *ckks.PublicKey
	sk, pk, _ = kgen.NewKeyPair()

	// Encryptor
	var encryptor *ckks.Encryptor
	encryptor, _ = ckkscontext.NewEncryptor(pk)

	// Decryptor
	var decryptor *ckks.Decryptor
	decryptor, _ = ckkscontext.NewDecryptor(sk)

	// Values to encrypt
	values := make([]complex128, 1<<(logN-1))

	for i := 0; i < len(str); i++ {

		val := float64(int(str[i]))
		values[i] = complex(val, val)
	}

	fmt.Printf("HEAAN parameters : logN = %d, logQ = %d, levels = %d (%d bits), logPrecision = %d, logScale = %d, sigma = %f \n", logN, logQ, levels, 60+(levels-1)*logQ, ckkscontext.Precision(), scale, sigma)

	// Plaintext creation and encoding process
	plaintext := ckkscontext.NewPlaintext(levels-1, scale)

	// Encryption process
	var ciphertext *ckks.Ciphertext
	ciphertext, _ = encryptor.EncryptNew(plaintext)

	// Decryption process
	plaintext, _ = decryptor.DecryptNew(ciphertext)

	// Decoding process
	valuesTest := plaintext.DecodeComplex()

	fmt.Printf("\nInput: %s", str)
	fmt.Printf("\nCipher: %v\n\nDecrypted: ", ciphertext)

	for i := 0; i < len(str); i++ {

		ch := int(math.Round(real(valuesTest[i])))
		fmt.Printf("%s", string(ch))

	}

	// Hier wird die Zeit gemessen
	// Hier wird die Zeit gemessen
	elapsed := time.Since(start)
	log.Printf("\nBinomial took %s", elapsed)
	// Hier wird die Zeit gemessen
	// Hier wird die Zeit gemessen
}

Terminal:
//////////////////////////////////////
HEAAN parameters : logN = 10, logQ = 30, levels = 8 (270 bits), logPrecision = 13, logScale = 30, sigma = 3.190000 

Input: hallowelt

Cipher: &{[0xc000119680 0xc0001196a0] 0xc0000922c0 30 0xc0001196c0 true false}

Decrypted: 

2020/01/12 17:26:04 
Binomial took 18.9492ms
Process exiting with code: 0
