### ISSUE TITLE
Meaning of Baseline ratio

### ISSUE THREAD

**Issue by jon-chuang** [ldsec/lattigo#26]
https://homomorphicencryption.org/wp-content/uploads/2019/08/poster_2.pdf

What does baseline ratio mean? Is it single-core? I think it is lattigo operations in ms divided by SEAL operation in ms?

**Comment by ChristianMct** [comment]
That is correct. Note that the these values are quite outdated now.

**Comment by jon-chuang** [comment]
Ok, I would be happy to see updated numbers in a new poster. Also, stating this as a fact in a new poster would save some confusion.
