### ISSUE TITLE
What is the plan for zero-knowledge proofs? 

### ISSUE THREAD

**Issue by jon-chuang** [ldsec/lattigo#28]
Is this to ensure that the computation has been performed correctly before decryption occurs? Since if it is not performed correctly, couldn't this leak secrets like a model's parameters?

I may be interested in implementing this if I know where to start.

**Comment by ChristianMct** [comment]
Some form of zero-knowledge proofs primitives would indeed be required when considering stronger adversarial models. 

We have no plan or ongoing project in that direction for Lattigo. Its `ring` package could be used for that purpose, but we have not investigated that aspect yet.

**Comment by jon-chuang** [comment]
Just some resources:
[Succinct Non-Interactive Zero Knowledge
for a von Neumann Architecture](https://eprint.iacr.org/2013/879.pdf)

**Comment by ChristianMct** [comment]
Closing: discussion about the ZK layer with use-cases as described in #30 #32 will be taken offline.
