### ISSUE TITLE
Usage of Rescale

### ISSUE THREAD

**Issue by Dylan-yxn** [ldsec/lattigo#40]
Hi, when I use  Rescale() after Mul, the result is wrong. And it doesn't just happen occasionally.
Here is my code:
```
evaluator.MulRelin(result,encIn[i],rlk,result)
fmt.Println(math.Log2(result.Scale()))
evaluator.Rescale(result,params.Scale,result)
fmt.Println(math.Log2(result.Scale()))
```
if we decrypt after MulRelin, we will get the corrext answer. And we decrypt after Rescale(), we will get a huge answer . The answer is different every time. 

Here is one of answer:
![QMUTB_R)A%2DVJES0@AP B8](https://user-images.githubusercontent.com/50690229/76683323-3b78cf00-663e-11ea-8ad1-b162bad4a7e9.png)

**I wonder if my usage of Rescale () is wrong. How to use it correctly.**

**Comment by Dylan-yxn** [comment]
Errors after Resclae() occur in the DCKKS scheme, but I have tested that they do not occur in the CKKS scheme.

**Comment by ChristianMct** [comment]
Hello,

Is it possible to provide a minimal code reproducing the behavior ? In particular, how are you decrypting the ciphertext ?

**Comment by Dylan-yxn** [comment]
Thank you for your reply.
Here is my code:

```
....
//input
for j:= range pi.input{
	pi.input[j] = complex(1, 0)
}
/*CKG*/
...
/*RKG*/
...
```
```
	encoder := ckks.NewEncoder(params)
	encInputs := make([]*ckks.Ciphertext, N, N)
	encryptor := ckks.NewEncryptorFromPk(params, pk)
	for i := range encInputs {
		encInputs[i] = ckks.NewCiphertext(params, 1,params.MaxLevel(),params.Scale)
	}

	pt := ckks.NewPlaintext(params,params.MaxLevel(),params.Scale)
	for i, pi := range P {
		encoder.Encode(pt,pi.input,slots)
		encryptor.Encrypt(pt, encInputs[i])
	}

	evaluator := ckks.NewEvaluator(params)

	/*caculate*/
	result := encInputs[0]
	evaluator.MulRelin(result,encInputs[1],rlk,result)
	fmt.Println(math.Log2(result.Scale()))
	evaluator.Rescale(result,params.Scale,result)
	fmt.Println(math.Log2(result.Scale()))

        /*CKS*/
	zero := params.NewPolyQ()
	cksCombined := cks.AllocateShare()
	for _, pi := range P[1:] {
		cks.GenShare(pi.sk.Get(), zero, result, pi.cksShare)
	}
	encOut := ckks.NewCiphertext(params, 1,params.MaxLevel(),params.Scale)
	for _, pi := range P {
		cks.AggregateShares(pi.cksShare, cksCombined, cksCombined)
	}
	cks.KeySwitch(cksCombined,result, encOut)

       /*decrypt*/
	decryptor := ckks.NewDecryptor(params, P[0].sk)
	ptres := ckks.NewPlaintext(params,params.MaxLevel(),params.Scale)
	decryptor.Decrypt(encOut, ptres)
	res := encoder.Decode(ptres,slots)
	fmt.Printf(" %6f %6f %6f %6f %6f\n",
		round(res[0]), round(res[1]), round(res[2]), round(res[3]), round(res[4]))
```
If I didn't use Rescale (), I would get the correct answer, but I got the following answer after using:
![IKY1F}X`MBIH%Y6I6F%31VG](https://user-images.githubusercontent.com/50690229/76919429-da821d00-6903-11ea-956c-bba86c4d668d.png)

**Comment by Pro7ech** [comment]
Thank you very much. I'll take a look and get back to you as soon as I figured out what is going on.

**Comment by Pro7ech** [comment]
There is something I do not understand in your code. You do 
- result -> CKS(zero) -> encOut
- encOut -> Decrypt -> ptres
-> ptres -> Decode -> res 

The CKS already decrypts the ciphertext if you switch to the key zero, therefor all you need to to is to call encOut.Plaintext() to switch the element to a type plaintext and be able to decode it.

**Comment by Dylan-yxn** [comment]
Thanks for your reminder. 
`res := encoder.Decode(encOut.Plaintext(),slots)`

But after decrypting, the answer still has the same error.

**Comment by Pro7ech** [comment]
Could you give me a link go your entire go file? It will be easier for me to find where the bug is occuring

**Comment by Dylan-yxn** [comment]
Here is my code:
https://github.com/Dylan-yxn/examples_dckks

**Comment by Pro7ech** [comment]
I found what was going wrong and why the rescale made it decrypt bad. 

First, I was wrong, your decryption code was correct, it was partially decrypting to the secret-key of P[0], and then P[0] would finish the decryption with his own key, you can revert the code to how it was previously. 

Then the wrong decryption is occurring because

`encOut := ckks.NewCiphertext(params, 1, params.MaxLevel(), params.Scale)`

is created at max level. But the level of the ciphertext after you rescale is reduced by one, so instead you should use 

`encOut := ckks.NewCiphertext(params, 1, result.Level(), params.Scale)`

Tell me if it fixes it

**Comment by Dylan-yxn** [comment]
I tried:
`encOut := ckks.NewCiphertext(params, 1 ,result.Level(),result.Scale())`
and
`encOut := ckks.NewCiphertext(params, 1 ,result.Level(),params.Scale)`
But it didn't work.
![QYN1}88IIVH9Y{MX7HF3J%I](https://user-images.githubusercontent.com/50690229/76953931-7a629980-694a-11ea-8486-cf76f3ea1373.png)

**Comment by Pro7ech** [comment]
Did you revert the code to its original decryption state?

**Comment by Dylan-yxn** [comment]
Thank you for your explanation. It can now be decrypted normally.
