### ISSUE TITLE
Fetch Public key and Private Key

### ISSUE THREAD

**Issue by AmitKawad** [ldsec/lattigo#46]
How can I fetch the public key and secret key to store them in a file/vault, the keys obtained are as follows ******&{0xc00000ccc0}&{[0xc00000cce0 0xc00000cd00]}.The Get() method returns a byte array, how can I get a base64 string of the keys

**Comment by ChristianMct** [comment]
Hi @AmitKawad,

The keys and other cryptographic objects comply to the `BinaryMarshaler` and `BinaryUnmarshaler` interfaces in the [encoding](https://golang.org/pkg/encoding/#BinaryMarshaler) package. You can the interfaces methods to convert from and to `[]byte`.

For base64 encoding and decoding, you may want to use the `base64` [subpackage](https://golang.org/pkg/encoding/base64/) of `encoding`.

**Comment by AmitKawad** [comment]
@ChristianMct 
Once I get the base64 string of the keys. How can I convert them back to their original form?  
Could you please show that with an example

**Comment by ChristianMct** [comment]
Again, on the Lattigo side, the `BinaryUnmarshaler` interface for keys is all you need to read the `[]byte` format of keys.

For example, let

```
sk := NewKeyGenerator(DefaultParams[PN12QP109]).GenSecretKey()
```

You can write it to a file by using the ioutils package:

```
skBytes, _ := sk.MarshalBinary()
ioutil.WriteFile("alice.sk", []byte(base64.StdEncoding.EncodeToString(skBytes)), 0640)
```

And read it back using the same package:
```
skBase64, _ := ioutil.ReadFile("alice.sk")
skBytes, _ := base64.StdEncoding.DecodeString(string(skBase64))
var sk SecretKey
sk.UnmarshalBinary(skBytes)
```

**Comment by ChristianMct** [comment]
Since this does not concern the library itself, I'm closing the issue.
