### ISSUE TITLE
Right Rotate may be wrong

### ISSUE THREAD

**Issue by Dylan-yxn** [ldsec/lattigo#49]
Ckks scheme, I tried to use RotateColumns () function, but got the wrong answer.

I tried to find the cause of the error, and finally found that when commenting out part of the code of the RotateColumns () function, the result will be correct. But this may slow down the efficiency of rotation.

**The commented code is:**
```
// if utils.HammingWeight64(k) <= utils.HammingWeight64((eval.ckksContext.n>>1)-k) {
					eval.rotateColumnsLPow2(ct0, k, evakey, ctOut)
				// } else {
				// 	eval.rotateColumnsRPow2(ct0, (eval.ckksContext.n>>1)-k, evakey, ctOut)
				// }

```
So I guess the cause of the error may be related to right rotation.

**Comment by Pro7ech** [comment]
Hello Dylan, 

Thank you for your feedback. Could you tell me more about the parameters and the rotations amount that you used so that I can look into it?

**Comment by Dylan-yxn** [comment]
Thank you for your reply.
I didn't find the error when I tried. Maybe I made a mistake.
