### ISSUE TITLE
Question about calling MulRelin multiple times

### ISSUE THREAD

**Issue by killalau** [ldsec/lattigo#54]
I want to test about the accuracy for the multiplication, so I implement a for loop to use `MulRelin` to calculate `1.1 ^ 20`. I found that `c2` would become 0 start from `i = 10`. Do I miss some function call to fix / minimize the errors?

```go
values := make([]complex128, slots)
values[0] = complex(1.1, 0)
txt := ckks.NewPlaintext(params, params.MaxLevel(), params.Scale)
encoder.Encode(txt, values, slots)
c1 := encryptor.EncryptNew(txt)
c2 := encryptor.EncryptNew(txt)
for i := 0; i < 20; i++ {
	evaluator.MulRelin(c2, c1, nil, c2)
	evaluator.Relinearize(c2, rlk, c2)
	evaluator.Rescale(c2, params.Scale, c2)
}
```

**Comment by ChristianMct** [comment]
Reducing the error of a CKKS ciphertext requires the [bootstrapping operation](https://eprint.iacr.org/2018/153.pdf), which is not yet part of Lattigo, but will be in the near future.

More generally, the real challenge in using the scheme remains the parametrization and the minimization of the circuit depth. By using the `ckks.DefaultParams[ckks.PN15QP880]` parameters set, the loop in your example is correct up to `i=16` or so. Minimization of the circuit depth indeed depends on the setting. For your particular example of a power, the `evaluator.Power` function aims to do exactly that. However, the results are worst than for the chained multiplication. I'll open a separated issue regarding that.

**Comment by Pro7ech** [comment]
To add some precision, the way you compute x^{20} has a depth of 20 and the parameters that you use do not allow for that much depth. But it can be computed with a depth of log(20) by using the generic polynomial evaluator of the library :
```
coeffs := []float64{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1} #the coefficients of x^{20}
ciphertext = params.evaluator.EvaluatePolyFast(ciphertext, coeffs, rlk)
```
It will minimize both the depth and the number of operations.

**Comment by killalau** [comment]
Thank you for your reply, so current the the library can only allow around 17 times chain multiplication. I need to wait for bootstrapping operation. 

Do you know is there any other library (maybe in other language) had already implemented the bootstrapping ?

**Comment by Pro7ech** [comment]
As far as I am aware of, the only public implementation of the bootstrapping for CKKS can be found in the HEAAN library. Some other libraries implement bootstrapping but for different schemes.
