### ISSUE TITLE
Documentation isn't completely idiomatic Go

### ISSUE THREAD

**Issue by gtank** [ldsec/lattigo#6]
Hey folks! This is really cool work and I'm looking forward to exploring. It could be much more legible to Go developers if you documented your functions and types using the canonical [godoc](https://blog.golang.org/godoc-documenting-go-code) formatting. I see that some of the code does this already, but some of it uses others styles of documentation (e.g. https://github.com/lca1/lattigo/blob/master/ring/float128.go)

This will allow both https://godoc.org and the local `godoc` [tool](https://godoc.org/golang.org/x/tools/cmd/godoc) to automatically parse your code as it updates. That way you won't have to make a new [graphic](https://github.com/lca1/lattigo/blob/master/documentation/RING.png) for every release :)

**Comment by ChristianMct** [comment]
Hey gtank, thanks for your interest in Lattigo. We are in the process of producing richer and more idiomatic Go documentation as a part of our roadmap toward v1.0 (expected in Sept.).
