### ISSUE TITLE
Generic Protocol(s) to transform an encryption to shares (and the opposite)

### ISSUE THREAD

**Issue by froelich** [ldsec/lattigo#62]
It would be nice to have a generic protocol to switch from a collectively encrypted ciphertext to (additive) secret shares, each held by one of the parties. I think that all the necessary components are already part of the refresh protocol and could be just decoupled from there.
It can make sense to have the "shares to ciphertext" protocol alongside, even though this protocol is probably very similar to a collective aggregation.
Thanks !

**Comment by ChristianMct** [comment]
I agree, the refresh protocol can be factorized. This would also make it match its definition in the paper.
