### ISSUE TITLE
CKKS Bootstrapping with level0 cipher

### ISSUE THREAD

**Issue by fionser** [ldsec/lattigo#63]
This ScaleUp [step](https://github.com/ldsec/lattigo/blob/master/ckks/bootstrapp.go#L17) will consume one level before the modUp. As the result, the CKKS bootstrapping function only take care of cipher that with level >= 1, which is a stronger requirements.

**Comment by Pro7ech** [comment]
Hello fionser, 

What the scale up step does is multiply the ciphertext by round(Q0/2^{10})/(InputScale), to bring the scale of the ciphertext as close to the ratio Q0/2^{10} as possible,  so this step does not consume any level as it is only a constant multiplication followed by an arbitrary set of the ciphertext scale. 

There is however the requirement that InputScale <= Q0/(2^{10}), but that is a property needed for the bootstrapping itself (you want that the ratio between Q0 and the scale of your message be large enough to enable a precise enough approximation of the homomorphic modular reduction).

You have to check that your input scale is smaller or equal to  Q0/(2^{10}) and as close as possible to a power of two (which should be possible as our polynomial evaluation algorithm is scale invariant and plaintext/ciphertext operations can be made scale invariant easily).
