### ISSUE TITLE
Wrong paper cited at CHANGELOG?

### ISSUE THREAD

**Issue by pdroalves** [ldsec/lattigo#68]
I'm trying to learn about the algorithm used for bootstrapping the CKKS at Lattigo and found a reference to the original BFV paper on the most recent [changelog](https://github.com/ldsec/lattigo/blob/master/CHANGELOG.md) for version 2.0.0. Is that write and Lattigo's CKKS uses BFV's bootstrap algorithm? Or maybe I miss understood the citation?

**Comment by Pro7ech** [comment]
Hello, you are right, there was a mistake. I corrected it (https://eprint.iacr.org/2020/1203). Thank you very much
