### ISSUE TITLE
[ckks] Bug when encoding which non power-of-two slots

### ISSUE THREAD

**Issue by simonwicky** [ldsec/lattigo#79]
Hi,

When trying to use the CKKS encoder, I encountered a bug during encoding. If I try to encode a dummy value with the slots parameter being a non power-of-two, the operation hangs. This can be simply reproduced using the following code.

`params := ckks.DefaultParams[0]`
`encoder := ckks.NewEncoder(params)`
`values := []complex128{complex(1, 0), complex(2, 0), complex(3, 0)}`
`plaintext := encoder.EncodeNew(values, 3)`

The issue can be traced back to `ckks/encoder.go:126`, where the value check for slots seems to be incorrectly performed.  If `slots != 0` the condition fails, the power-of-two check is not executed and the execution is carried on, with an incorrect `slots`value, which then cause the inverse FFT to hangs.
I believe this can be fixed by correcting the `&&` into a `||` to ensure both checks are performed.

**Comment by ChristianMct** [comment]
Hi @simonwicky ,

Thanks for pointing this out. We'll fix that bug as a part of #80.
