### ISSUE TITLE
Updated Lattigo Benchmarks

### ISSUE THREAD

**Issue by mdeib** [ldsec/lattigo#82]
The most recent benchmarks I could find for lattigo's performance are on this poster: [https://homomorphicencryption.org/wp-content/uploads/2019/08/poster_2.pdf](url). These results, however, are comparing SEAL 3.2 and a much older version of lattigo as well. As a lot has changed in both libraries since then, it would be good to have some more updated benchmarks of Lattigo's performance vs SEAL.

**Comment by ChristianMct** [comment]
Hi @mdeib 

We do have a more recent benchmark comparison, that we'll be able to make public soon. Stay tuned!

In the meantime, you can use the `go test -bench` command, which will run the full benchmarking suite of Lattigo.

**Comment by Pro7ech** [comment]
You will find the most recent benchmarks in the [demo paper](https://homomorphicencryption.org/wp-content/uploads/2020/12/wahc20_demo_christian.pdf) of WAHC 2020.
