### ISSUE TITLE
Missing MarshalBinary and UnmarshalBinary functions in dckks

### ISSUE THREAD

**Issue by ffsinger** [ldsec/lattigo#87]
Hi,

While trying to send shares over the network, I noticed that some types in package `dckks` do not implement the functions `MarshalBinary` and `UnmarshalBinary`. This is the case for `RTGShare`, `CKGShare`, `CKSShare` and `PCKSShare`. Currently only `RKGShare` does implement it.

This enhancement would simplify the use of these protocols.

Notice that package `dbfv` implements them, so it may be possible to reuse this code with only little changes.

**Comment by ChristianMct** [comment]
Thanks for pointing this out. This is going to be fixed as a part of a common feature extraction between the `dbfv` and `dckks` packages. As you rightfully observed, the shares types are identical.
