### ISSUE TITLE
Updating the oblivious driver example (BFV) to use actual lat/long data (signed data)

### ISSUE THREAD

**Issue by amlwwalker** [ldsec/lattigo#91]
Hi,
I think I am right in saying that BFV is not capable of doing math on encrypted floating point numbers. For my own education really (and perhaps others) I am trying to update the example to take a lat/long coordinate for the rider's location, convert this to signed integers and then continue the process to work out which driver is closest to the rider.

* The first thing I have done is set the lat/long of the rider
* Then I convert the lat/long to an integer, by multiplying by 1000 and rounding.
* Next I have set each driver's location to something similar to the rider +/- a bit of randomness
* Due to the fact that my values can be negative (lat/long can be negative) I have updated the example to use int64 instead of uint64.
* Finally I need to calculate the expected and actual distances. This is where I am getting an error.

My code example is below. I believe the issue is on this line:

`result := encoder.DecodeIntNew(decryptor.DecryptNew(evaluator.MulNew(RiderCiphertext, RiderCiphertext)))`

The issue being its tricky for me to see exactly what that line is doing - but apparently its working out the distance between the rider and every driver...(?) - One question - is there another way to write that so that its more 'mathsy' - i.e a bit more like the `distance()` function - but for encrypted values, or is the reason its in this format precisely the point of lattice approaches to HE?

I haven't done it yet, but the last step will be to convert the distance back to a float and divide by 1000 to get the actual distance.

One step I am not sure about is whether I can use this encryption method to then send the closest driver the rider's actual location so that they can decrypt it and go there. Can the public key of the driver be used then by the rider to encrypt their location and send it to the driver who can then decrypt it, and is this comparable to RSA or AES encryption in efficiency and security? 

This is a really nice example of how you could use HE btw - thanks for providing it, it would be cool if I could get it to use actual lat/long for my own peace of mind! Thank you all!

full code snippet:

```go
package main

import (
	"fmt"
	"math"
	"math/rand"

	"github.com/ldsec/lattigo/v2/bfv"
)

func obliviousRiding() {

	// Number of drivers in the area
	nbDrivers := uint64(5) //max is N //2048 max

	// BFV parameters (128 bit security) with plaintext modulus 65929217
	params := bfv.DefaultParams[bfv.PN13QP218].WithT(0x3ee0001)

	encoder := bfv.NewEncoder(params)

	// Rider's keygen
	kgen := bfv.NewKeyGenerator(params)

	riderSk, riderPk := kgen.GenKeyPair()

	decryptor := bfv.NewDecryptor(params, riderSk)

	encryptorRiderPk := bfv.NewEncryptorFromPk(params, riderPk)

	encryptorRiderSk := bfv.NewEncryptorFromSk(params, riderSk)

	evaluator := bfv.NewEvaluator(params)

	fmt.Println("============================================")
	fmt.Println("Homomorphic computations on batched integers")
	fmt.Println("============================================")
	fmt.Println()
	fmt.Printf("Parameters : N=%d, T=%d, Q = %d bits, sigma = %f \n",
		1<<params.LogN(), params.T(), params.LogQP(), params.Sigma())
	fmt.Println()
	// Rider coordinates [x, y, x, y, ....., x, y]
	riderPosX := int64(math.Round(51.5014 * 1000)) //buckingham palace
	riderPosY := int64(math.Round(-0.1419 * 1000))

	fmt.Printf("riderPosX %d, riderPoxY %d\r\n", riderPosX, riderPosY)
	Rider := make([]int64, 1<<params.LogN())
	for i := uint64(0); i < nbDrivers; i++ {
		Rider[(i << 1)] = riderPosX
		Rider[(i<<1)+1] = riderPosY
	}

	riderPlaintext := bfv.NewPlaintext(params)
	encoder.EncodeInt(Rider, riderPlaintext)

	// driversData coordinates [0, 0, ..., x, y, ..., 0, 0]
	driversData := make([][]int64, nbDrivers)

	driversPlaintexts := make([]*bfv.Plaintext, nbDrivers)

	min := -500 //add some randomness to drivers positions
	max := 500  //add some randomness to drivers positions
	fmt.Println(rand.Intn(max - min) + min)

	for i := uint64(0); i < nbDrivers; i++ {
		driversData[i] = make([]int64, 1<<params.LogN())
		driversData[i][(i << 1)] = riderPosY + int64(rand.Intn(max - min) + min)
		driversData[i][(i<<1)+1] = riderPosY + int64(rand.Intn(max - min) + min)
		driversPlaintexts[i] = bfv.NewPlaintext(params)
		encoder.EncodeInt(driversData[i], driversPlaintexts[i])
	}
	k := 3
	driversData[k] = make([]int64, 1<<params.LogN())
	driversData[k][(k << 1)] = riderPosX
	driversData[k][(k<<1)+1] = riderPosY
	driversPlaintexts[k] = bfv.NewPlaintext(params)
	encoder.EncodeInt(driversData[k], driversPlaintexts[k])

	fmt.Printf("Encrypting %d driversData (x, y) and 1 Rider (%d, %d) \n",
		nbDrivers, riderPosX, riderPosY)
	fmt.Println()

	RiderCiphertext := encryptorRiderSk.EncryptNew(riderPlaintext)

	DriversCiphertexts := make([]*bfv.Ciphertext, nbDrivers)
	for i := uint64(0); i < nbDrivers; i++ {
		DriversCiphertexts[i] = encryptorRiderPk.EncryptNew(driversPlaintexts[i])
	}

	fmt.Println("Computing encrypted distance = ((CtD1 + CtD2 + CtD3 + CtD4...) - CtR)^2 ...")
	fmt.Println()

	evaluator.Neg(RiderCiphertext, RiderCiphertext)
	for i := uint64(0); i < nbDrivers; i++ {
		evaluator.Add(RiderCiphertext, DriversCiphertexts[i], RiderCiphertext)
	}

	result := encoder.DecodeIntNew(decryptor.DecryptNew(evaluator.MulNew(RiderCiphertext, RiderCiphertext)))

	minIndex, minPosX, minPosY, minDist := uint64(0), int64(0), int64(0), float64(0)
	errors := 0

	for i := uint64(0); i < nbDrivers; i++ {

		driverPosX, driverPosY := driversData[i][i<<1], driversData[i][(i<<1)+1]

		computedDist := math.Abs(float64(result[i<<1] + result[(i<<1)+1]))
		expectedDist := math.Abs(float64(distance(driverPosX, driverPosY, riderPosX, riderPosY)))
		fmt.Printf("x %d y %d calculated %.2f expected %.2f\r\n", driverPosX, driverPosY, computedDist, expectedDist)
		if computedDist == expectedDist {
			if computedDist < minDist {
				minIndex = i
				minPosX, minPosY = driverPosX, driverPosY
				minDist = computedDist
			}
		} else {
			errors++
		}

		if i < 4 || i > nbDrivers-5 {
			fmt.Printf("Distance with Driver %d : %8f = (%4d - %4d)^2 + (%4d - %4d)^2 --> correct: %t\n",
				i, computedDist, driverPosX, riderPosX, driverPosY, riderPosY, computedDist == expectedDist)
		}

		if i == nbDrivers>>1 {
			fmt.Println("...")
		}
	}

	fmt.Printf("\nFinished with %.2f%% errors\n\n", 100*float64(errors)/float64(nbDrivers))
	fmt.Printf("Closest Driver to Rider is n°%d (%d, %d) with a distance of %d units\n",
		minIndex, minPosX, minPosY, uint64(math.Sqrt(float64(minDist))))
}

func distance(a, b, c, d int64) int64 {
	if a > c {
		a, c = c, a
	}
	if b > d {
		b, d = d, b
	}
	x, y := a-c, b-d
	return x*x + y*y
}

func main() {
	obliviousRiding()
}
```

**Comment by Pro7ech** [comment]
Hello amlwwalker, 

The circuit is computing _d = (x_i - x)^2 + (y_i - y)^2_, hence _d_ should be smaller than your plaintext modulus 65929217 (divided by two if you want to keep the sign). However you encrypt values as large as 51501, so the computation _(x_i - 51501)^2_ has a high probability of being larger than 65929217. You must either reduce the upper-bound on the inputs or increase the plaintext modulus accordingly (it must be a prime and congruent to 1 mod 2N).

**Comment by amlwwalker** [comment]
Thanks for your response @Pro7ech - really helpful.

First test was to lower the size of the values and that worked perfectly. I need to keep the accuracy to 3dp (*1000) however so I am attempting to increase the plaintext modulus. The next prime number that is bigger than the possible values I will be feeding it with is `2652353003`. However (from testing) I also can see this is apparently not fulfilling the second requirement

```
panic: invalid modulus (Modulus[0] != 1 mod 2N)
```

But my understanding of "congruent to 1 mod 2N" is lacking. What is N in this case and my understanding of congruence is that my prime is equal to the area of a right angle triangle thats sides are made up of rational numbers, however I suspect that isn't the definition here. Is this documented within the repository for me to do some further reading?

Thanks again

**Comment by Pro7ech** [comment]
For T, a plaintext modulus, congruent to 1 mod 2N means that T-1 is divisible by 2N, where N is the degree of your ring (params.N()). This prime should work for N=2^13 (the parameters that you use) : 0x9e188001.

However, the BFV scheme is very sensitive to the size of the plaintext modulus, the larger it is, the more noise is generated and the less operations you can do. 32 bits is quite large for a plaintext modulus, especially for such small parameters, and I'm quite sure multiplication, especially squaring, will fail. 

To be fair, the BFV scheme is a good starting point to get introduced to FHE, but as if you are looking to do any serious arithmetic, be it on integers or floating point, the CKKS scheme is the go-to scheme. It is faster and much more versatile than the BFV scheme, but also much harder to use properly, especially for its full RNS variant.  From my experience, the only real life cases where BFV is as good as CKKS is when the circuit is limited to very simple operations (scalar products and additions). 

The main downside of CKKS is that it can only encrypt N/2 complex values (although this is not quite true because a real variant allows to encrypt N real values). However, for some circuits, such as computing x^2 + y^2, the imaginary part can be cleverly used double the throughput. For example (x + i*y)^2 = x^2 + y^2 + i*2*x*y uses only one complex slot.

**Comment by amlwwalker** [comment]
Hi @Pro7ech 

Thanks so much for this, yeah I originally looked at CKKS as I knew that it could handle floating points but was a bit much to jump straight in on.

After your advice towards the end (yeah that large prime takes too long to process with the ..... parameters) I ended up with this:
I got a site to generate 50 random lat/longs around Buckingham Palace and it comes with the actual distances between Buck House and the lat/long pair. The following runs smoothly and picks out "Driver 38" as the closest driver. We are using pythagoras which on the earth is inaccurate but I think close enough although makes bug hunting harder :)

It responds with 
```
Closest Driver to Rider is n°38 (51.49, -0.09) with a distance of **330.42 KM** (using pythag). Actual distance is **4.7829 km**
```

Thats obviously not the same as the actual distance (or close). Im probably making a simple error somewhere but any ideas why that might not be playing ball?
Thanks

```go
package main

import (
	"fmt"
	"github.com/ldsec/lattigo/v2/bfv"
	"math"
)
var latitudes = [...]float64 {51.55505845, 51.35049502, 51.49342404, 51.35576144, 51.46367303, 51.59827867, 51.44975987, 51.41530716, 51.51790999, 51.52325115, 51.37090813, 51.48248203, 51.48224685, 51.57928026, 51.41250126, 51.59095946, 51.55059409, 51.60192801, 51.57055526, 51.43968032, 51.42249985, 51.60153806, 51.44619761, 51.41079237, 51.52254237, 51.32881429, 51.52059371, 51.54308946, 51.42119378, 51.62363479, 51.46497323, 51.49570821, 51.6119193, 51.53123382, 51.60930381, 51.61608966, 51.5484012, 51.55255689, 51.4864284, 51.63758953, 51.43994719, 51.53815565, 51.46523161, 51.5708527, 51.59856109, 51.45217381, 51.34832873, 51.38392884, 51.63273957, 51.59322371}
var longs = [...]float64 {-0.03196547,-0.19744777, 0.03596891,-0.00561684,-0.06120532,-0.23269885,-0.38122187,-0.32031603, 0.10251308, 0.02074109,-0.22620037,-0.32248626,-0.27654621,-0.32562411,-0.2569608,-0.3761417,-0.32063787,-0.30631856,-0.22557072,-0.22545223,-0.33839268,-0.10436118, 0.07544437,-0.23393792,-0.2254365,-0.13135078, 0.0740383,-0.39272936, 0.09767021,-0.07333396, 0.0615448, 0.05258168,-0.29546331,-0.31173471,-0.00397991,-0.05041521,-0.37625559,-0.08845615,-0.09096628,-0.19127254}
var distances = [...]string {"9.9542 km","17.587 km","13.1179 km","19.5754 km","7.8838 km","11.6607 km","17.0457 km","15.4079 km","17.6936 km","12.1346 km","15.8837 km","12.0684 km","8.9977 km","14.4866 km","12.6845 km","18.1274 km","12.6506 km","15.0644 km","8.7768 km","8.9553 km","15.8929 km","11.1229 km","17.132 km","12.013 km","5.3769 km","19.7726 km","15.7559 km","17.1335 km","19.7342 km","14.1698 km","15.5074 km","14.2388 km","15.3759 km","11.3774 km","15.3979 km","14.1205 km","16.1901 km","6.8024 km","4.7829 km","14.8703 km","13.2825 km","13.7532 km","15.5078 km","17.665 km","18.3112 km","7.142 km","17.7673 km","14.172 km","15.1218 km","12.0783 km"}

func obliviousRiding() {

	// Number of drivers in the area
	nbDrivers := uint64(40) //max is N //2048 max

	// BFV parameters (128 bit security) with plaintext modulus 65929217 --> 0x3ee0001
	// need to be able to find values up to 51000 so need a prime that is 2652353003 or greater
	// from https://github.com/ldsec/lattigo/issues/91 using prime number 0x20008001
	params := bfv.DefaultParams[bfv.PN14QP438].WithT(0x20008001)

	encoder := bfv.NewEncoder(params)

	// Rider's keygen
	kgen := bfv.NewKeyGenerator(params)

	riderSk, riderPk := kgen.GenKeyPair()

	decryptor := bfv.NewDecryptor(params, riderSk)

	encryptorRiderPk := bfv.NewEncryptorFromPk(params, riderPk)

	encryptorRiderSk := bfv.NewEncryptorFromSk(params, riderSk)

	evaluator := bfv.NewEvaluator(params)

	fmt.Println("============================================")
	fmt.Println("Homomorphic computations on batched integers")
	fmt.Println("============================================")
	fmt.Println()
	fmt.Printf("Parameters : N=%d, T=%d, Q = %d bits, sigma = %f \n",
		1<<params.LogN(), params.T(), params.LogQP(), params.Sigma())
	fmt.Println()
	const scaler = 318
	// Rider coordinates [x, y, x, y, ....., x, y]
	riderPosX := int64(math.Round(51.5014*scaler)) //buckingham palace
	riderPosY := int64(math.Round(-0.1419*scaler))

	fmt.Printf("riderPosX %d, riderPoxY %d\r\n", riderPosX, riderPosY)
	Rider := make([]int64, 1<<params.LogN())
	for i := uint64(0); i < nbDrivers; i++ {
		Rider[(i << 1)] = riderPosX
		Rider[(i<<1)+1] = riderPosY
	}

	riderPlaintext := bfv.NewPlaintext(params)
	encoder.EncodeInt(Rider, riderPlaintext)

	// driversData coordinates [0, 0, ..., x, y, ..., 0, 0]
	driversData := make([][]int64, nbDrivers)

	driversPlaintexts := make([]*bfv.Plaintext, nbDrivers)
	for i := uint64(0); i < nbDrivers; i++ {

		driversData[i] = make([]int64, 1<<params.LogN())
		driversData[i][(i << 1)] = int64(math.Round(latitudes[i]*scaler))//driversData[i][i<<1] + xRand
		driversData[i][(i<<1)+1] =int64(math.Round(longs[i]*scaler))
		driversPlaintexts[i] = bfv.NewPlaintext(params)
		encoder.EncodeInt(driversData[i], driversPlaintexts[i])
	}

	fmt.Printf("Encrypting %d driversData (x, y) and 1 Rider (%d, %d) \n",
		nbDrivers, riderPosX, riderPosY)
	fmt.Println()

	RiderCiphertext := encryptorRiderSk.EncryptNew(riderPlaintext)

	DriversCiphertexts := make([]*bfv.Ciphertext, nbDrivers)
	for i := uint64(0); i < nbDrivers; i++ {
		DriversCiphertexts[i] = encryptorRiderPk.EncryptNew(driversPlaintexts[i])
	}

	fmt.Println("Computing encrypted distance = ((CtD1 + CtD2 + CtD3 + CtD4...) - CtR)^2 ...")
	fmt.Println()

	evaluator.Neg(RiderCiphertext, RiderCiphertext)
	for i := uint64(0); i < nbDrivers; i++ {
		evaluator.Add(RiderCiphertext, DriversCiphertexts[i], RiderCiphertext)
	}

	result := encoder.DecodeIntNew(decryptor.DecryptNew(evaluator.MulNew(RiderCiphertext, RiderCiphertext)))

	minIndex, minPosX, minPosY, minDist := uint64(0), int64(0), int64(0), float64(0)
	errors := 0

	for i := uint64(0); i < nbDrivers; i++ {

		driverPosX, driverPosY := driversData[i][i<<1], driversData[i][(i<<1)+1]

		computedDist := math.Abs(float64(result[i<<1] + result[(i<<1)+1]))
		expectedDist := math.Abs(float64(distance(driverPosX, driverPosY, riderPosX, riderPosY)))
		//fmt.Printf("x %d y %d calculated %.2f expected %.2f\r\n", driverPosX, driverPosY, computedDist, expectedDist)
		if computedDist == expectedDist {
			if i == 0 {
				minIndex = i
				minDist = computedDist
			} else if computedDist < minDist {
				minIndex = i
				minPosX, minPosY = driverPosX, driverPosY
				minDist = computedDist
				fmt.Println(i, "minDist ", minDist)
			}
		} else {
			errors++
		}

		if i < 4 || i > nbDrivers-5 {
			fmt.Printf("Distance with Driver %d : %8f = (%4d - %4d)^2 + (%4d - %4d)^2 --> correct: %t\n",
				i, computedDist, driverPosX, riderPosX, driverPosY, riderPosY, computedDist == expectedDist)
		}

		if i == nbDrivers>>1 {
			fmt.Println("...")
		}
	}

	fmt.Printf("\nFinished with %.2f%% errors\n\n", 100*float64(errors)/float64(nbDrivers))
	fmt.Printf("Closest Driver to Rider is n°%d (%.2f, %.2f) with a distance of %.2f KM (using pythag). Actual distance is %s\n",
		minIndex, float64(minPosX)/scaler, float64(minPosY)/scaler, 6371 * math.Sqrt(float64(minDist))/scaler, distances[minIndex])
}

func distance(a, b, c, d int64) int64 {
	if a > c {
		a, c = c, a
	}
	if b > d {
		b, d = d, b
	}
	x, y := a-c, b-d
	return x*x + y*y
}

func main() {
	obliviousRiding()
}
```

**Comment by Pro7ech** [comment]
The BFV circuit correctly evaluates what it is asked to do, however computing the [distance between two latitudes and longitudes](https://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula) isn't the same as computing the distance between two points on a grid.

**Comment by amlwwalker** [comment]
Thanks yeah I knew about that, just didn't expect it to be quite so different!
I can happily update that distance function but the calculatedDistance equation: `((CtD1 + CtD2 + CtD3 + CtD4...) - CtR)^2 ...")`  for the circuit, which I think is happening here `	result := encoder.DecodeIntNew(decryptor.DecryptNew(evaluator.MulNew(RiderCiphertext, RiderCiphertext)))` is a little more involved - is the Haversine formula possible to turn into a BFV circuit? Can BFV handle the operations?

**Comment by Pro7ech** [comment]
No it can't, BFV provides vectorized integer modular arithmetic. You would need to use the CKKS scheme. But even then, it would be much more efficient to first convert from a spherical coordinate system to some other more HE friendly coordinate system.
