### ISSUE TITLE
Can Lattigo support the Fully-Threshold MHE right now?

### ISSUE THREAD

**Issue by supplyout** [ldsec/lattigo#97]
Hi, I read the paper _Lattigo: a Multiparty Homomorphic Encryption Library in Go_ recently, I find this :

> Full-threshold variants of BFV and CKKS are implemented in a development branch of Lattigo

but I can't find any branch which implemented the Fully-Threshold MHE. So I want to know is this still a on-goning work or I just missing it?
thanks

**Comment by ChristianMct** [comment]
Hi @supplyout,

The full-threshold functionalities are still an on-going implementation work. The good news is that we will have somebody working on their integration in the main code-base, starting end of February.
