### ISSUE TITLE
Some question about fully threshold FHE in lattigo

### ISSUE THREAD

**Issue by HIT1180300227** [ldsec/lattigo#99]
Hi ,in the previous issue, you said that the part about the fully threshold of lattigo was being processed, so I would like to ask you some related questions.

  In Dan Boneh‘s paper- "Threshold Cryptosystems From Threshold Fully Homomorphic Encryption", this paper proposed a method to develop a general approach to adding a threshold functionality to a nonthreshold cryptographic schemes.

  Generally,by using secret share scheme(like linear secret sharing or Shamir secret sharing scheme)on FHE's private key SK,the fully threshold can be achieved.Does the on-going fully threshold part of lattigo follow the same idea?

**Comment by ChristianMct** [comment]
This question was answered via the mailing list.

**Comment by HIT1180300227** [comment]
Here is professor Christian Mouchet's answer:

We are currently trying to map the full-threshold functionality we are exploring in Lattigo to the related work. I'm afraid that, until we complete this process, we won't be able to answer many questions or release the code.

Indeed, it relies on the general approach you mentioned of using secret-sharing techniques on the secret-keys of the FHE scheme. However, it seems that our approach is simpler than the one in Boneh's paper and we need to understand what the implications are. In essence, it is closer to the share re-sharing approach suggested by Asharov et al. in "Multiparty computation with low communication, computation and interaction via threshold FHE"  In Annual International Conference on the Theory and Applications of Cryptographic Techniques, pages 483–501. Springer,2012. (Which is indeed a paper I would recommend you to read if you haven't already, although it focuses mainly on the N-out-of-N-threshold case and less in fully-threshold one).
